### ISSUE TITLE
Write procedure for riff:list% chunks

### ISSUE THREAD

**Issue by wcs4217** [lwhjp/binary-class-riff#1]
The write procedure for `riff:list%` chunks, `(λ (out v) (write-riff-list v out))`, calls `write-riff-list` with its arguments swapped.  This makes `write-wave` unusable, because it raises a exception like:

```
in-list: contract violation
  expected: list?
  given: #<output-port:...>
```

**Comment by lwhjp** [comment]
Thanks - I've pushed a fix.
